Quick commit

diff --git a/scripts/bin/extract b/scripts/bin/extract
--- a/scripts/bin/extract
+++ b/scripts/bin/extract
@@ -3,28 +3,28 @@
 
 set -e
 
-if [ -f $1 ]; then
-  case $1 in
-    *.tar.bz2) tar -jxvf $1 ;;
-    *.tar.gz) tar -zxvf $1 ;;
-    *.bz2) bunzip2 $1 ;;
-    *.dmg) hdiutil mount $1 ;;
-    *.gz) gunzip $1 ;;
-    *.tar) tar -xvf $1 ;;
-    *.tbz2) tar -jxvf $1 ;;
-    *.tgz) tar -zxvf $1 ;;
-    *.zip) unzip $1 ;;
-    *.ZIP) unzip $1 ;;
-    *.pax) cat $1 | pax -r ;;
-    *.pax.Z) uncompress $1 --stdout | pax -r ;;
-    *.rar) unrar x $1 ;;
-    *.Z) uncompress $1 ;;
+if [ -f "$1" ]; then
+  case "$1" in
+    *.tar.bz2) tar -jxvf "$1" ;;
+    *.tar.gz) tar -zxvf "$1" ;;
+    *.bz2) bunzip2 "$1" ;;
+    *.dmg) hdiutil mount "$1" ;;
+    *.gz) gunzip "$1" ;;
+    *.tar) tar -xvf "$1" ;;
+    *.tbz2) tar -jxvf "$1" ;;
+    *.tgz) tar -zxvf "$1" ;;
+    *.zip) unzip "$1" ;;
+    *.ZIP) unzip "$1" ;;
+    *.pax) cmd "$1" | pax -r ;;
+    *.pax.Z) uncompress "$1" --stdout | pax -r ;;
+    *.rar) unrar x "$1" ;;
+    *.Z) uncompress "$1" ;;
     *)
-      printf "'$1' cannot be extracted/mounted via extract().\n" >&2
+      printf '%s cannot be extracted/mounted via extract().\n' "$1" >&2
       exit 1
       ;;
   esac
 else
-  printf "'$1' is not a valid file.\n" >&2
+  printf '%s is not a valid file.\n' "$1" >&2
   exit 1
 fi
