Quick commit

diff --git a/scripts/bin/set-default-python b/scripts/bin/set-default-python
--- a/scripts/bin/set-default-python
+++ b/scripts/bin/set-default-python
@@ -1,10 +1,10 @@
 #!/usr/bin/env bash
 # Set up system default python version to 3.8
 
-_default_python() {
+if which python3.8 >/dev/null; then
   ln -s -f "$(which python3.8)" /usr/local/bin/python
   printf 'python3.8 symlinked to default.\n' && exit 0
-}
-
-which python3.8 >/dev/null && _default_python ||
-  printf 'python3.8 not found.\n' >&2 && exit 1
+else
+  printf 'python3.8 not found.\n' >&2
+  exit 1
+fi
